# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: stretch_arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_left_wheel
    - joint_head_pan
    - joint_head_tilt
    - joint_lift
    - joint_arm_l3
    - joint_arm_l2
    - joint_arm_l1
    - joint_arm_l0
    - joint_wrist_yaw
    - joint_gripper_finger_left
    - joint_gripper_finger_right
    - joint_right_wheel
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - joint_lift
    - joint_arm_l3
    - joint_arm_l2
    - joint_arm_l1
    - joint_arm_l0
    - joint_wrist_yaw
  gains:
    joint_lift:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_arm_l3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_arm_l2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_arm_l1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_arm_l0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_wrist_yaw:
      p: 100
      d: 1
      i: 1
      i_clamp: 1