controller_list:
  - name: fake_stretch_arm_controller
    type: $(arg execution_type)
    joints:
      - virtual_joint
      - joint_lift
      - joint_arm_l3
      - joint_arm_l2
      - joint_arm_l1
      - joint_arm_l0
      - joint_wrist_yaw
  - name: fake_stretch_gripper_controller
    type: $(arg execution_type)
    joints:
      - joint_gripper_finger_left
      - joint_gripper_finger_right
initial:  # Define initial robot poses.
  - group: stretch_arm
    pose: home
  - group: stretch_gripper
    pose: home